---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-exporter
  labels:
    helm.sh/chart: jaeger-exporter-0.1.0
    app.kubernetes.io/name: jaeger-exporter
    app.kubernetes.io/instance: jaeger-exporter
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jaeger-exporter
    app.kubernetes.io/instance: jaeger-exporter
